name: Build Twine Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download and setup Tweego
      run: |
        # Download Tweego zip file
        wget -q https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip
        echo "Downloaded zip file"
        
        # Extract and list contents to see structure
        unzip -q tweego-2.1.1-linux-x64.zip
        echo "Archive contents:"
        ls -la
        
        # Find all tweego executables and make them executable
        find . -name "tweego" -type f -exec chmod +x {} \;
        
        # Find the tweego executable path and move it to a standard location
        TWEEGO_PATH=$(find . -name "tweego" -type f | head -1)
        echo "Found tweego at: $TWEEGO_PATH"
        
        # Copy tweego to /usr/local/bin so it's available in PATH
        sudo cp "$TWEEGO_PATH" /usr/local/bin/tweego
        
        # Verify tweego works from PATH
        tweego --version || echo "Version command completed"
        echo "Tweego setup completed successfully"
        
    - name: Create build directory
      run: mkdir -p build
      
    - name: Build game with Tweego
      run: |
        # Use tweego from PATH
        echo "Using tweego from PATH"
        tweego --version || echo "Version check completed"
        
        # Check passages directory contents
        echo "Passages directory contents:"
        ls -la passages/
        
        # Check twee file contents briefly
        echo "Checking twee files:"
        for file in passages/*.twee; do
          echo "=== $file ==="
          head -5 "$file"
        done
        
        echo "Running tweego build..."
        # Try building with story formats included
        if tweego -o build/game.html passages/ storyformats/ -v; then
          echo "Build completed successfully with storyformats"
          echo "Output file info:"
          ls -la build/game.html
          echo "File size: $(stat -c%s build/game.html) bytes"
        else
          echo "Build failed, trying without storyformats directory..."
          if tweego -o build/game.html passages/ -v; then
            echo "Build completed successfully without storyformats"
            echo "Output file info:"
            ls -la build/game.html
          else
            echo "Build failed completely"
            exit 1
          fi
        fi
        
    - name: List build contents
      run: ls -la build/
      
    - name: Upload game artifact
      uses: actions/upload-artifact@v4
      with:
        name: twine-game
        path: build/game.html
        
    - name: Deploy to GitHub Pages (if on main branch)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: game